# Generated by Django 5.2.5 on 2025-08-29 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Mobile phone number must starts with 010, 011, 012 or 015 having the length of 11 digits.', regex='^01[0125]\\d{8}$')]),
        ),
    ]
